name: Tonomy ID CI/CD

on:
    push:
        branches:
            - '*'
            - development

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            - name: ðŸ— Setup repo
              uses: actions/checkout@v3

            - name: ðŸ“¦ Build node_modules
              uses: actions/setup-node@v3
              with:
                  node-version: 16.4.1
            - run: npm install

            - name: ðŸ“¦ Add built artifacts
              uses: actions/upload-artifact@v3
              with:
                name: node_modules
                path: ./node_modules

    test:
        needs: build
        runs-on: ubuntu-20.04
        
        steps:
            - name: ðŸ— Setup repo
              uses: actions/checkout@v3

            - name: ðŸ“¦ Get built from artifacts
              uses: actions/download-artifact@v3
              with:
                name: node_modules
                path: ./node_modules

            - name: ðŸ› ï¸ Unit tests
              uses: actions/setup-node@v3
              with:
                  node-version: 16.4.1
            - run: npm test

    deploy:
        needs: [build, test]
        runs-on: ubuntu-20.04
        
        steps:
            - name: ðŸ— Setup repo
              uses: actions/checkout@v3

            - name: ðŸ“¦ Get built from artifacts
              uses: actions/download-artifact@v3
              with:
                name: node_modules
                path: ./node_modules

            # https://github.com/expo/expo-github-action
            - name: ðŸ— Setup Expo
              uses: expo/expo-github-action@v7
              with:
                expo-version: 47.0.0
                expo-cache: false
                eas-version: 3.1.0
                eas-cache: false
                packager: npm
                token: ${{ secrets.EXPO_TOKEN }}

            - name: ðŸš€ Build and publish app
              env:
                NODE_ENV: staging
                SUPER_SECRET: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
            - run: echo "${GOOGLE_SERVICE_ACCOUNT_KEY}"" > google-service-key.json
            - run: npm run deploy:android