# name: Tonomy ID Continuous Integration

# on:
#     pull_request

# jobs:
#     build:
#         runs-on: ubuntu-20.04

#         steps:
#             - name: ğŸ— Setup repo
#               uses: actions/checkout@v3

#             - name: ğŸ“¦ Build and test
#               uses: actions/setup-node@v3
#               with:
#                   node-version: 16.4.1
#             - run: npm install
#             - run: npm test